# fly.toml app configuration file generated for taller-vibe-api-green-snow-8356
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taller-vibe-api-green-snow-8356'
primary_region = 'iad'

[build]
  builder = "heroku"

[env]
  NODE_ENV = "production"
  DB_PATH = '/app/data/asistencia.db'

[[mounts]]
  source = 'taller_vibe_data'
  destination = '/app/data'

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
